version: "3.4"
name: docker_essentials
services:
  webapi:
    image: titan-biometric:latest
    pull_policy: always
    container_name: webapi
    networks:
      - docker_essentials
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5433;Database=Biometric_Signals;User Id=postgres;Password=.,.
    ports:
      - 5080:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - docker_essentials
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=.,.
      - PGPORT=5433
    ports:
      - 5432:5433
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdata:

networks:
  docker_essentials:
    name: docker_essentials