version: '3.4'

services:
  titanbiometric.api:
    image: titan-biometric:latest
    container_name: titanbiometric.api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 80:80
    depends_on:
        postgres:
            condition: service_healthy
  
  titanbiometric.db:
    image: postgres:latest
    container_name: titanbiometric.db
    environment:
      - POSTGRES_DB=Biometric_Signals
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=.,.
    volumes:
      - ./.containers/titanbiometric-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  
